/* ../verilog/matrixTranspose/src/crossbarShiftUp64x64.v
 * This file is automatically generated by Chi Zhang
 * k = 4, M = 16
 */
module crossbarShiftUp64x64 # (
  parameter DATA_WIDTH = 32
) (
  input [1-1:0] clk,
  input [1-1:0] clk_en,
  input [1-1:0] start,
  input [1-1:0] reset,
  input [DATA_WIDTH-1:0] in0,
  input [DATA_WIDTH-1:0] in1,
  input [DATA_WIDTH-1:0] in2,
  input [DATA_WIDTH-1:0] in3,
  input [DATA_WIDTH-1:0] in4,
  input [DATA_WIDTH-1:0] in5,
  input [DATA_WIDTH-1:0] in6,
  input [DATA_WIDTH-1:0] in7,
  input [DATA_WIDTH-1:0] in8,
  input [DATA_WIDTH-1:0] in9,
  input [DATA_WIDTH-1:0] in10,
  input [DATA_WIDTH-1:0] in11,
  input [DATA_WIDTH-1:0] in12,
  input [DATA_WIDTH-1:0] in13,
  input [DATA_WIDTH-1:0] in14,
  input [DATA_WIDTH-1:0] in15,
  input [DATA_WIDTH-1:0] in16,
  input [DATA_WIDTH-1:0] in17,
  input [DATA_WIDTH-1:0] in18,
  input [DATA_WIDTH-1:0] in19,
  input [DATA_WIDTH-1:0] in20,
  input [DATA_WIDTH-1:0] in21,
  input [DATA_WIDTH-1:0] in22,
  input [DATA_WIDTH-1:0] in23,
  input [DATA_WIDTH-1:0] in24,
  input [DATA_WIDTH-1:0] in25,
  input [DATA_WIDTH-1:0] in26,
  input [DATA_WIDTH-1:0] in27,
  input [DATA_WIDTH-1:0] in28,
  input [DATA_WIDTH-1:0] in29,
  input [DATA_WIDTH-1:0] in30,
  input [DATA_WIDTH-1:0] in31,
  input [DATA_WIDTH-1:0] in32,
  input [DATA_WIDTH-1:0] in33,
  input [DATA_WIDTH-1:0] in34,
  input [DATA_WIDTH-1:0] in35,
  input [DATA_WIDTH-1:0] in36,
  input [DATA_WIDTH-1:0] in37,
  input [DATA_WIDTH-1:0] in38,
  input [DATA_WIDTH-1:0] in39,
  input [DATA_WIDTH-1:0] in40,
  input [DATA_WIDTH-1:0] in41,
  input [DATA_WIDTH-1:0] in42,
  input [DATA_WIDTH-1:0] in43,
  input [DATA_WIDTH-1:0] in44,
  input [DATA_WIDTH-1:0] in45,
  input [DATA_WIDTH-1:0] in46,
  input [DATA_WIDTH-1:0] in47,
  input [DATA_WIDTH-1:0] in48,
  input [DATA_WIDTH-1:0] in49,
  input [DATA_WIDTH-1:0] in50,
  input [DATA_WIDTH-1:0] in51,
  input [DATA_WIDTH-1:0] in52,
  input [DATA_WIDTH-1:0] in53,
  input [DATA_WIDTH-1:0] in54,
  input [DATA_WIDTH-1:0] in55,
  input [DATA_WIDTH-1:0] in56,
  input [DATA_WIDTH-1:0] in57,
  input [DATA_WIDTH-1:0] in58,
  input [DATA_WIDTH-1:0] in59,
  input [DATA_WIDTH-1:0] in60,
  input [DATA_WIDTH-1:0] in61,
  input [DATA_WIDTH-1:0] in62,
  input [DATA_WIDTH-1:0] in63,
  output reg [1-1:0] start_next_stage,
  output reg [DATA_WIDTH-1:0] out0,
  output reg [DATA_WIDTH-1:0] out1,
  output reg [DATA_WIDTH-1:0] out2,
  output reg [DATA_WIDTH-1:0] out3,
  output reg [DATA_WIDTH-1:0] out4,
  output reg [DATA_WIDTH-1:0] out5,
  output reg [DATA_WIDTH-1:0] out6,
  output reg [DATA_WIDTH-1:0] out7,
  output reg [DATA_WIDTH-1:0] out8,
  output reg [DATA_WIDTH-1:0] out9,
  output reg [DATA_WIDTH-1:0] out10,
  output reg [DATA_WIDTH-1:0] out11,
  output reg [DATA_WIDTH-1:0] out12,
  output reg [DATA_WIDTH-1:0] out13,
  output reg [DATA_WIDTH-1:0] out14,
  output reg [DATA_WIDTH-1:0] out15,
  output reg [DATA_WIDTH-1:0] out16,
  output reg [DATA_WIDTH-1:0] out17,
  output reg [DATA_WIDTH-1:0] out18,
  output reg [DATA_WIDTH-1:0] out19,
  output reg [DATA_WIDTH-1:0] out20,
  output reg [DATA_WIDTH-1:0] out21,
  output reg [DATA_WIDTH-1:0] out22,
  output reg [DATA_WIDTH-1:0] out23,
  output reg [DATA_WIDTH-1:0] out24,
  output reg [DATA_WIDTH-1:0] out25,
  output reg [DATA_WIDTH-1:0] out26,
  output reg [DATA_WIDTH-1:0] out27,
  output reg [DATA_WIDTH-1:0] out28,
  output reg [DATA_WIDTH-1:0] out29,
  output reg [DATA_WIDTH-1:0] out30,
  output reg [DATA_WIDTH-1:0] out31,
  output reg [DATA_WIDTH-1:0] out32,
  output reg [DATA_WIDTH-1:0] out33,
  output reg [DATA_WIDTH-1:0] out34,
  output reg [DATA_WIDTH-1:0] out35,
  output reg [DATA_WIDTH-1:0] out36,
  output reg [DATA_WIDTH-1:0] out37,
  output reg [DATA_WIDTH-1:0] out38,
  output reg [DATA_WIDTH-1:0] out39,
  output reg [DATA_WIDTH-1:0] out40,
  output reg [DATA_WIDTH-1:0] out41,
  output reg [DATA_WIDTH-1:0] out42,
  output reg [DATA_WIDTH-1:0] out43,
  output reg [DATA_WIDTH-1:0] out44,
  output reg [DATA_WIDTH-1:0] out45,
  output reg [DATA_WIDTH-1:0] out46,
  output reg [DATA_WIDTH-1:0] out47,
  output reg [DATA_WIDTH-1:0] out48,
  output reg [DATA_WIDTH-1:0] out49,
  output reg [DATA_WIDTH-1:0] out50,
  output reg [DATA_WIDTH-1:0] out51,
  output reg [DATA_WIDTH-1:0] out52,
  output reg [DATA_WIDTH-1:0] out53,
  output reg [DATA_WIDTH-1:0] out54,
  output reg [DATA_WIDTH-1:0] out55,
  output reg [DATA_WIDTH-1:0] out56,
  output reg [DATA_WIDTH-1:0] out57,
  output reg [DATA_WIDTH-1:0] out58,
  output reg [DATA_WIDTH-1:0] out59,
  output reg [DATA_WIDTH-1:0] out60,
  output reg [DATA_WIDTH-1:0] out61,
  output reg [DATA_WIDTH-1:0] out62,
  output reg [DATA_WIDTH-1:0] out63
);

  reg [2-1:0] timestamp;

  always@(posedge clk) begin
    if (reset) begin
      start_next_stage <= 1'b0;
      timestamp <= 2'b00;
    end else if (clk_en & start) begin
      start_next_stage <= start;
      timestamp <= timestamp + 1;
    end
  end

  always@(posedge clk) begin
    if (clk_en & start) begin
      case (timestamp)
        2'b00: begin
          out0 <= in0;
          out1 <= in1;
          out2 <= in2;
          out3 <= in3;
          out4 <= in4;
          out5 <= in5;
          out6 <= in6;
          out7 <= in7;
          out8 <= in8;
          out9 <= in9;
          out10 <= in10;
          out11 <= in11;
          out12 <= in12;
          out13 <= in13;
          out14 <= in14;
          out15 <= in15;
          out16 <= in16;
          out17 <= in17;
          out18 <= in18;
          out19 <= in19;
          out20 <= in20;
          out21 <= in21;
          out22 <= in22;
          out23 <= in23;
          out24 <= in24;
          out25 <= in25;
          out26 <= in26;
          out27 <= in27;
          out28 <= in28;
          out29 <= in29;
          out30 <= in30;
          out31 <= in31;
          out32 <= in32;
          out33 <= in33;
          out34 <= in34;
          out35 <= in35;
          out36 <= in36;
          out37 <= in37;
          out38 <= in38;
          out39 <= in39;
          out40 <= in40;
          out41 <= in41;
          out42 <= in42;
          out43 <= in43;
          out44 <= in44;
          out45 <= in45;
          out46 <= in46;
          out47 <= in47;
          out48 <= in48;
          out49 <= in49;
          out50 <= in50;
          out51 <= in51;
          out52 <= in52;
          out53 <= in53;
          out54 <= in54;
          out55 <= in55;
          out56 <= in56;
          out57 <= in57;
          out58 <= in58;
          out59 <= in59;
          out60 <= in60;
          out61 <= in61;
          out62 <= in62;
          out63 <= in63;
        end
        2'b01: begin
          out0 <= in4;
          out1 <= in5;
          out2 <= in6;
          out3 <= in7;
          out4 <= in8;
          out5 <= in9;
          out6 <= in10;
          out7 <= in11;
          out8 <= in12;
          out9 <= in13;
          out10 <= in14;
          out11 <= in15;
          out12 <= in16;
          out13 <= in17;
          out14 <= in18;
          out15 <= in19;
          out16 <= in20;
          out17 <= in21;
          out18 <= in22;
          out19 <= in23;
          out20 <= in24;
          out21 <= in25;
          out22 <= in26;
          out23 <= in27;
          out24 <= in28;
          out25 <= in29;
          out26 <= in30;
          out27 <= in31;
          out28 <= in32;
          out29 <= in33;
          out30 <= in34;
          out31 <= in35;
          out32 <= in36;
          out33 <= in37;
          out34 <= in38;
          out35 <= in39;
          out36 <= in40;
          out37 <= in41;
          out38 <= in42;
          out39 <= in43;
          out40 <= in44;
          out41 <= in45;
          out42 <= in46;
          out43 <= in47;
          out44 <= in48;
          out45 <= in49;
          out46 <= in50;
          out47 <= in51;
          out48 <= in52;
          out49 <= in53;
          out50 <= in54;
          out51 <= in55;
          out52 <= in56;
          out53 <= in57;
          out54 <= in58;
          out55 <= in59;
          out56 <= in60;
          out57 <= in61;
          out58 <= in62;
          out59 <= in63;
          out60 <= in0;
          out61 <= in1;
          out62 <= in2;
          out63 <= in3;
        end
        2'b10: begin
          out0 <= in8;
          out1 <= in9;
          out2 <= in10;
          out3 <= in11;
          out4 <= in12;
          out5 <= in13;
          out6 <= in14;
          out7 <= in15;
          out8 <= in16;
          out9 <= in17;
          out10 <= in18;
          out11 <= in19;
          out12 <= in20;
          out13 <= in21;
          out14 <= in22;
          out15 <= in23;
          out16 <= in24;
          out17 <= in25;
          out18 <= in26;
          out19 <= in27;
          out20 <= in28;
          out21 <= in29;
          out22 <= in30;
          out23 <= in31;
          out24 <= in32;
          out25 <= in33;
          out26 <= in34;
          out27 <= in35;
          out28 <= in36;
          out29 <= in37;
          out30 <= in38;
          out31 <= in39;
          out32 <= in40;
          out33 <= in41;
          out34 <= in42;
          out35 <= in43;
          out36 <= in44;
          out37 <= in45;
          out38 <= in46;
          out39 <= in47;
          out40 <= in48;
          out41 <= in49;
          out42 <= in50;
          out43 <= in51;
          out44 <= in52;
          out45 <= in53;
          out46 <= in54;
          out47 <= in55;
          out48 <= in56;
          out49 <= in57;
          out50 <= in58;
          out51 <= in59;
          out52 <= in60;
          out53 <= in61;
          out54 <= in62;
          out55 <= in63;
          out56 <= in0;
          out57 <= in1;
          out58 <= in2;
          out59 <= in3;
          out60 <= in4;
          out61 <= in5;
          out62 <= in6;
          out63 <= in7;
        end
        2'b11: begin
          out0 <= in12;
          out1 <= in13;
          out2 <= in14;
          out3 <= in15;
          out4 <= in16;
          out5 <= in17;
          out6 <= in18;
          out7 <= in19;
          out8 <= in20;
          out9 <= in21;
          out10 <= in22;
          out11 <= in23;
          out12 <= in24;
          out13 <= in25;
          out14 <= in26;
          out15 <= in27;
          out16 <= in28;
          out17 <= in29;
          out18 <= in30;
          out19 <= in31;
          out20 <= in32;
          out21 <= in33;
          out22 <= in34;
          out23 <= in35;
          out24 <= in36;
          out25 <= in37;
          out26 <= in38;
          out27 <= in39;
          out28 <= in40;
          out29 <= in41;
          out30 <= in42;
          out31 <= in43;
          out32 <= in44;
          out33 <= in45;
          out34 <= in46;
          out35 <= in47;
          out36 <= in48;
          out37 <= in49;
          out38 <= in50;
          out39 <= in51;
          out40 <= in52;
          out41 <= in53;
          out42 <= in54;
          out43 <= in55;
          out44 <= in56;
          out45 <= in57;
          out46 <= in58;
          out47 <= in59;
          out48 <= in60;
          out49 <= in61;
          out50 <= in62;
          out51 <= in63;
          out52 <= in0;
          out53 <= in1;
          out54 <= in2;
          out55 <= in3;
          out56 <= in4;
          out57 <= in5;
          out58 <= in6;
          out59 <= in7;
          out60 <= in8;
          out61 <= in9;
          out62 <= in10;
          out63 <= in11;
        end
      endcase
    end
  end

endmodule
