/* ../verilog/matrixTranspose/src/crossbarShiftUp.v
 * This file is automatically generated by Chi Zhang
 * k = 2, M = 16
 */
module crossbarShiftUp # (
  parameter DATA_WIDTH = 32
) (
  input [1-1:0] clk,
  input [1-1:0] clk_en,
  input [1-1:0] start,
  input [1-1:0] reset,
  input [DATA_WIDTH-1:0] in0,
  input [DATA_WIDTH-1:0] in1,
  input [DATA_WIDTH-1:0] in2,
  input [DATA_WIDTH-1:0] in3,
  input [DATA_WIDTH-1:0] in4,
  input [DATA_WIDTH-1:0] in5,
  input [DATA_WIDTH-1:0] in6,
  input [DATA_WIDTH-1:0] in7,
  input [DATA_WIDTH-1:0] in8,
  input [DATA_WIDTH-1:0] in9,
  input [DATA_WIDTH-1:0] in10,
  input [DATA_WIDTH-1:0] in11,
  input [DATA_WIDTH-1:0] in12,
  input [DATA_WIDTH-1:0] in13,
  input [DATA_WIDTH-1:0] in14,
  input [DATA_WIDTH-1:0] in15,
  input [DATA_WIDTH-1:0] in16,
  input [DATA_WIDTH-1:0] in17,
  input [DATA_WIDTH-1:0] in18,
  input [DATA_WIDTH-1:0] in19,
  input [DATA_WIDTH-1:0] in20,
  input [DATA_WIDTH-1:0] in21,
  input [DATA_WIDTH-1:0] in22,
  input [DATA_WIDTH-1:0] in23,
  input [DATA_WIDTH-1:0] in24,
  input [DATA_WIDTH-1:0] in25,
  input [DATA_WIDTH-1:0] in26,
  input [DATA_WIDTH-1:0] in27,
  input [DATA_WIDTH-1:0] in28,
  input [DATA_WIDTH-1:0] in29,
  input [DATA_WIDTH-1:0] in30,
  input [DATA_WIDTH-1:0] in31,
  output reg [1-1:0] start_next_stage,
  output reg [DATA_WIDTH-1:0] out0,
  output reg [DATA_WIDTH-1:0] out1,
  output reg [DATA_WIDTH-1:0] out2,
  output reg [DATA_WIDTH-1:0] out3,
  output reg [DATA_WIDTH-1:0] out4,
  output reg [DATA_WIDTH-1:0] out5,
  output reg [DATA_WIDTH-1:0] out6,
  output reg [DATA_WIDTH-1:0] out7,
  output reg [DATA_WIDTH-1:0] out8,
  output reg [DATA_WIDTH-1:0] out9,
  output reg [DATA_WIDTH-1:0] out10,
  output reg [DATA_WIDTH-1:0] out11,
  output reg [DATA_WIDTH-1:0] out12,
  output reg [DATA_WIDTH-1:0] out13,
  output reg [DATA_WIDTH-1:0] out14,
  output reg [DATA_WIDTH-1:0] out15,
  output reg [DATA_WIDTH-1:0] out16,
  output reg [DATA_WIDTH-1:0] out17,
  output reg [DATA_WIDTH-1:0] out18,
  output reg [DATA_WIDTH-1:0] out19,
  output reg [DATA_WIDTH-1:0] out20,
  output reg [DATA_WIDTH-1:0] out21,
  output reg [DATA_WIDTH-1:0] out22,
  output reg [DATA_WIDTH-1:0] out23,
  output reg [DATA_WIDTH-1:0] out24,
  output reg [DATA_WIDTH-1:0] out25,
  output reg [DATA_WIDTH-1:0] out26,
  output reg [DATA_WIDTH-1:0] out27,
  output reg [DATA_WIDTH-1:0] out28,
  output reg [DATA_WIDTH-1:0] out29,
  output reg [DATA_WIDTH-1:0] out30,
  output reg [DATA_WIDTH-1:0] out31
);

  reg [3-1:0] timestamp;

  always@(posedge clk) begin
    if (reset) begin
      start_next_stage <= 1'b0;
      timestamp <= 3'b000;
    end else if (clk_en & start) begin
      start_next_stage <= start;
      timestamp <= timestamp + 1;
    end
  end

  always@(posedge clk) begin
    if (clk_en & start) begin
      case (timestamp)
        3'b000: begin
          out0 <= in0;
          out1 <= in1;
          out2 <= in2;
          out3 <= in3;
          out4 <= in4;
          out5 <= in5;
          out6 <= in6;
          out7 <= in7;
          out8 <= in8;
          out9 <= in9;
          out10 <= in10;
          out11 <= in11;
          out12 <= in12;
          out13 <= in13;
          out14 <= in14;
          out15 <= in15;
          out16 <= in16;
          out17 <= in17;
          out18 <= in18;
          out19 <= in19;
          out20 <= in20;
          out21 <= in21;
          out22 <= in22;
          out23 <= in23;
          out24 <= in24;
          out25 <= in25;
          out26 <= in26;
          out27 <= in27;
          out28 <= in28;
          out29 <= in29;
          out30 <= in30;
          out31 <= in31;
        end
        3'b001: begin
          out0 <= in2;
          out1 <= in3;
          out2 <= in4;
          out3 <= in5;
          out4 <= in6;
          out5 <= in7;
          out6 <= in8;
          out7 <= in9;
          out8 <= in10;
          out9 <= in11;
          out10 <= in12;
          out11 <= in13;
          out12 <= in14;
          out13 <= in15;
          out14 <= in16;
          out15 <= in17;
          out16 <= in18;
          out17 <= in19;
          out18 <= in20;
          out19 <= in21;
          out20 <= in22;
          out21 <= in23;
          out22 <= in24;
          out23 <= in25;
          out24 <= in26;
          out25 <= in27;
          out26 <= in28;
          out27 <= in29;
          out28 <= in30;
          out29 <= in31;
          out30 <= in0;
          out31 <= in1;
        end
        3'b010: begin
          out0 <= in4;
          out1 <= in5;
          out2 <= in6;
          out3 <= in7;
          out4 <= in8;
          out5 <= in9;
          out6 <= in10;
          out7 <= in11;
          out8 <= in12;
          out9 <= in13;
          out10 <= in14;
          out11 <= in15;
          out12 <= in16;
          out13 <= in17;
          out14 <= in18;
          out15 <= in19;
          out16 <= in20;
          out17 <= in21;
          out18 <= in22;
          out19 <= in23;
          out20 <= in24;
          out21 <= in25;
          out22 <= in26;
          out23 <= in27;
          out24 <= in28;
          out25 <= in29;
          out26 <= in30;
          out27 <= in31;
          out28 <= in0;
          out29 <= in1;
          out30 <= in2;
          out31 <= in3;
        end
        3'b011: begin
          out0 <= in6;
          out1 <= in7;
          out2 <= in8;
          out3 <= in9;
          out4 <= in10;
          out5 <= in11;
          out6 <= in12;
          out7 <= in13;
          out8 <= in14;
          out9 <= in15;
          out10 <= in16;
          out11 <= in17;
          out12 <= in18;
          out13 <= in19;
          out14 <= in20;
          out15 <= in21;
          out16 <= in22;
          out17 <= in23;
          out18 <= in24;
          out19 <= in25;
          out20 <= in26;
          out21 <= in27;
          out22 <= in28;
          out23 <= in29;
          out24 <= in30;
          out25 <= in31;
          out26 <= in0;
          out27 <= in1;
          out28 <= in2;
          out29 <= in3;
          out30 <= in4;
          out31 <= in5;
        end
        3'b100: begin
          out0 <= in8;
          out1 <= in9;
          out2 <= in10;
          out3 <= in11;
          out4 <= in12;
          out5 <= in13;
          out6 <= in14;
          out7 <= in15;
          out8 <= in16;
          out9 <= in17;
          out10 <= in18;
          out11 <= in19;
          out12 <= in20;
          out13 <= in21;
          out14 <= in22;
          out15 <= in23;
          out16 <= in24;
          out17 <= in25;
          out18 <= in26;
          out19 <= in27;
          out20 <= in28;
          out21 <= in29;
          out22 <= in30;
          out23 <= in31;
          out24 <= in0;
          out25 <= in1;
          out26 <= in2;
          out27 <= in3;
          out28 <= in4;
          out29 <= in5;
          out30 <= in6;
          out31 <= in7;
        end
        3'b101: begin
          out0 <= in10;
          out1 <= in11;
          out2 <= in12;
          out3 <= in13;
          out4 <= in14;
          out5 <= in15;
          out6 <= in16;
          out7 <= in17;
          out8 <= in18;
          out9 <= in19;
          out10 <= in20;
          out11 <= in21;
          out12 <= in22;
          out13 <= in23;
          out14 <= in24;
          out15 <= in25;
          out16 <= in26;
          out17 <= in27;
          out18 <= in28;
          out19 <= in29;
          out20 <= in30;
          out21 <= in31;
          out22 <= in0;
          out23 <= in1;
          out24 <= in2;
          out25 <= in3;
          out26 <= in4;
          out27 <= in5;
          out28 <= in6;
          out29 <= in7;
          out30 <= in8;
          out31 <= in9;
        end
        3'b110: begin
          out0 <= in12;
          out1 <= in13;
          out2 <= in14;
          out3 <= in15;
          out4 <= in16;
          out5 <= in17;
          out6 <= in18;
          out7 <= in19;
          out8 <= in20;
          out9 <= in21;
          out10 <= in22;
          out11 <= in23;
          out12 <= in24;
          out13 <= in25;
          out14 <= in26;
          out15 <= in27;
          out16 <= in28;
          out17 <= in29;
          out18 <= in30;
          out19 <= in31;
          out20 <= in0;
          out21 <= in1;
          out22 <= in2;
          out23 <= in3;
          out24 <= in4;
          out25 <= in5;
          out26 <= in6;
          out27 <= in7;
          out28 <= in8;
          out29 <= in9;
          out30 <= in10;
          out31 <= in11;
        end
        3'b111: begin
          out0 <= in14;
          out1 <= in15;
          out2 <= in16;
          out3 <= in17;
          out4 <= in18;
          out5 <= in19;
          out6 <= in20;
          out7 <= in21;
          out8 <= in22;
          out9 <= in23;
          out10 <= in24;
          out11 <= in25;
          out12 <= in26;
          out13 <= in27;
          out14 <= in28;
          out15 <= in29;
          out16 <= in30;
          out17 <= in31;
          out18 <= in0;
          out19 <= in1;
          out20 <= in2;
          out21 <= in3;
          out22 <= in4;
          out23 <= in5;
          out24 <= in6;
          out25 <= in7;
          out26 <= in8;
          out27 <= in9;
          out28 <= in10;
          out29 <= in11;
          out30 <= in12;
          out31 <= in13;
        end
      endcase
    end
  end

endmodule
