// File: dff.v
// Generated by MyHDL 0.9.0
// Date: Wed Jun  8 23:07:09 2016


`timescale 1ns/10ps

module dff (
    clk,
    d,
    q
);


input clk;
input d;
output q;
reg q;






always @(posedge clk) begin: DFF_LOGIC
    q <= d;
end

endmodule
