// File: gcd.v
// Generated by MyHDL 0.9.0
// Date: Thu Jun  9 16:00:47 2016


`timescale 1ns/10ps

module gcd (
    clk,
    start,
    output,
    ready
);


input clk;
input start;
output output;
reg output;
output ready;
reg ready;






always @(posedge clk) begin: GCD_GCDLOGIC
    reg [5-1:0] inputB;
    reg [5-1:0] tempB;
    reg [5-1:0] tempA;
    reg [5-1:0] inputA;
    if (start) begin
        tempA <= inputA;
        tempB <= inputB;
    end
    else if ((tempA > tempB)) begin
        tempA <= (tempA - tempB);
    end
    else begin
        tempB <= (tempB - tempA);
    end
    output <= tempA;
    if ((tempB == 0)) begin
        ready <= 1;
        tempB <= 1;
    end
    if ((ready == 1)) begin
        ready <= 0;
    end
end

endmodule
