onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /afu_user_tb/afu_user_uut/clk
add wave -noupdate /afu_user_tb/afu_user_uut/reset
add wave -noupdate /afu_user_tb/afu_user_uut/input_fifo_din
add wave -noupdate /afu_user_tb/afu_user_uut/input_fifo_we
add wave -noupdate /afu_user_tb/afu_user_uut/input_fifo_full
add wave -noupdate /afu_user_tb/afu_user_uut/output_fifo_dout
add wave -noupdate /afu_user_tb/afu_user_uut/output_fifo_re
add wave -noupdate /afu_user_tb/afu_user_uut/output_fifo_empty
add wave -noupdate /afu_user_tb/afu_user_uut/input_fifo_dout
add wave -noupdate /afu_user_tb/afu_user_uut/input_fifo_re
add wave -noupdate /afu_user_tb/afu_user_uut/input_fifo_empty
add wave -noupdate /afu_user_tb/afu_user_uut/in0
add wave -noupdate /afu_user_tb/afu_user_uut/in1
add wave -noupdate /afu_user_tb/afu_user_uut/in2
add wave -noupdate /afu_user_tb/afu_user_uut/in3
add wave -noupdate /afu_user_tb/afu_user_uut/in4
add wave -noupdate /afu_user_tb/afu_user_uut/in5
add wave -noupdate /afu_user_tb/afu_user_uut/in6
add wave -noupdate /afu_user_tb/afu_user_uut/in7
add wave -noupdate /afu_user_tb/afu_user_uut/in8
add wave -noupdate /afu_user_tb/afu_user_uut/in9
add wave -noupdate /afu_user_tb/afu_user_uut/in10
add wave -noupdate /afu_user_tb/afu_user_uut/in11
add wave -noupdate /afu_user_tb/afu_user_uut/in12
add wave -noupdate /afu_user_tb/afu_user_uut/in13
add wave -noupdate /afu_user_tb/afu_user_uut/in14
add wave -noupdate /afu_user_tb/afu_user_uut/in15
add wave -noupdate /afu_user_tb/afu_user_uut/in16
add wave -noupdate /afu_user_tb/afu_user_uut/in17
add wave -noupdate /afu_user_tb/afu_user_uut/in18
add wave -noupdate /afu_user_tb/afu_user_uut/in19
add wave -noupdate /afu_user_tb/afu_user_uut/in20
add wave -noupdate /afu_user_tb/afu_user_uut/in21
add wave -noupdate /afu_user_tb/afu_user_uut/in22
add wave -noupdate /afu_user_tb/afu_user_uut/in23
add wave -noupdate /afu_user_tb/afu_user_uut/in24
add wave -noupdate /afu_user_tb/afu_user_uut/in25
add wave -noupdate /afu_user_tb/afu_user_uut/in26
add wave -noupdate /afu_user_tb/afu_user_uut/in27
add wave -noupdate /afu_user_tb/afu_user_uut/in28
add wave -noupdate /afu_user_tb/afu_user_uut/in29
add wave -noupdate /afu_user_tb/afu_user_uut/in30
add wave -noupdate /afu_user_tb/afu_user_uut/in31
add wave -noupdate /afu_user_tb/afu_user_uut/out0
add wave -noupdate /afu_user_tb/afu_user_uut/out1
add wave -noupdate /afu_user_tb/afu_user_uut/out2
add wave -noupdate /afu_user_tb/afu_user_uut/out3
add wave -noupdate /afu_user_tb/afu_user_uut/out4
add wave -noupdate /afu_user_tb/afu_user_uut/out5
add wave -noupdate /afu_user_tb/afu_user_uut/out6
add wave -noupdate /afu_user_tb/afu_user_uut/out7
add wave -noupdate /afu_user_tb/afu_user_uut/out8
add wave -noupdate /afu_user_tb/afu_user_uut/out9
add wave -noupdate /afu_user_tb/afu_user_uut/out10
add wave -noupdate /afu_user_tb/afu_user_uut/out11
add wave -noupdate /afu_user_tb/afu_user_uut/out12
add wave -noupdate /afu_user_tb/afu_user_uut/out13
add wave -noupdate /afu_user_tb/afu_user_uut/out14
add wave -noupdate /afu_user_tb/afu_user_uut/out15
add wave -noupdate /afu_user_tb/afu_user_uut/out16
add wave -noupdate /afu_user_tb/afu_user_uut/out17
add wave -noupdate /afu_user_tb/afu_user_uut/out18
add wave -noupdate /afu_user_tb/afu_user_uut/out19
add wave -noupdate /afu_user_tb/afu_user_uut/out20
add wave -noupdate /afu_user_tb/afu_user_uut/out21
add wave -noupdate /afu_user_tb/afu_user_uut/out22
add wave -noupdate /afu_user_tb/afu_user_uut/out23
add wave -noupdate /afu_user_tb/afu_user_uut/out24
add wave -noupdate /afu_user_tb/afu_user_uut/out25
add wave -noupdate /afu_user_tb/afu_user_uut/out26
add wave -noupdate /afu_user_tb/afu_user_uut/out27
add wave -noupdate /afu_user_tb/afu_user_uut/out28
add wave -noupdate /afu_user_tb/afu_user_uut/out29
add wave -noupdate /afu_user_tb/afu_user_uut/out30
add wave -noupdate /afu_user_tb/afu_user_uut/out31
add wave -noupdate /afu_user_tb/afu_user_uut/output_fifo_din
add wave -noupdate /afu_user_tb/afu_user_uut/start
add wave -noupdate /afu_user_tb/afu_user_uut/clk_en
add wave -noupdate /afu_user_tb/afu_user_uut/start_next_stage
add wave -noupdate /afu_user_tb/afu_user_uut/output_fifo_we
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {40 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 270
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {190 ns}
