onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/clk
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/clk_en
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/start
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/reset
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/in0
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/in1
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/in2
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/in3
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/in4
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/in5
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/in6
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/in7
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/in8
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/in9
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/in10
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/in11
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/in12
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/in13
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/in14
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/in15
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/in16
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/in17
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/in18
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/in19
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/in20
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/in21
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/in22
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/in23
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/in24
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/in25
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/in26
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/in27
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/in28
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/in29
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/in30
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/in31
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/start_next_stage
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/out0
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/out1
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/out2
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/out3
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/out4
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/out5
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/out6
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/out7
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/out8
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/out9
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/out10
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/out11
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/out12
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/out13
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/out14
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/out15
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/out16
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/out17
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/out18
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/out19
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/out20
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/out21
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/out22
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/out23
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/out24
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/out25
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/out26
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/out27
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/out28
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/out29
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/out30
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage0/out31
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {42 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {215 ns}
