onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/clk
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/clk_en
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/reset
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/start
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/in0
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/in1
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/in2
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/in3
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/in4
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/in5
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/in6
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/in7
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/in8
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/in9
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/in10
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/in11
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/in12
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/in13
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/in14
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/in15
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/in16
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/in17
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/in18
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/in19
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/in20
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/in21
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/in22
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/in23
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/in24
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/in25
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/in26
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/in27
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/in28
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/in29
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/in30
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/in31
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/start_next_stage
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/out0
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/out1
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/out2
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/out3
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/out4
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/out5
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/out6
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/out7
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/out8
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/out9
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/out10
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/out11
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/out12
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/out13
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/out14
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/out15
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/out16
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/out17
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/out18
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/out19
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/out20
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/out21
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/out22
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/out23
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/out24
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/out25
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/out26
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/out27
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/out28
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/out29
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/out30
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/out31
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage1/timestamp
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ns} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {1 us}
