onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/clk
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/clk_en
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/reset
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/start
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/in0
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/in1
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/in2
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/in3
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/in4
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/in5
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/in6
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/in7
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/in8
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/in9
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/in10
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/in11
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/in12
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/in13
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/in14
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/in15
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/in16
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/in17
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/in18
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/in19
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/in20
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/in21
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/in22
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/in23
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/in24
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/in25
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/in26
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/in27
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/in28
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/in29
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/in30
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/in31
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/out0
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/out1
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/out2
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/out3
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/out4
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/out5
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/out6
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/out7
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/out8
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/out9
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/out10
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/out11
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/out12
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/out13
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/out14
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/out15
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/out16
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/out17
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/out18
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/out19
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/out20
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/out21
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/out22
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/out23
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/out24
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/out25
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/out26
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/out27
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/out28
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/out29
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/out30
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/out31
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/start_next_stage
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/addr0_3
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/addr4_7
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/addr8_11
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/addr12_15
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/addr16_19
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/addr20_23
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/addr24_27
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/addr28_31
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/state
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage2/counter
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ns} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {1001 ns}
