onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/clk
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/clk_en
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/start
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/reset
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/in0
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/in1
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/in2
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/in3
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/in4
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/in5
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/in6
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/in7
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/in8
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/in9
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/in10
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/in11
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/in12
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/in13
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/in14
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/in15
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/in16
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/in17
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/in18
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/in19
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/in20
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/in21
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/in22
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/in23
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/in24
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/in25
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/in26
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/in27
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/in28
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/in29
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/in30
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/in31
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/start_next_stage
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/out0
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/out1
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/out2
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/out3
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/out4
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/out5
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/out6
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/out7
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/out8
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/out9
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/out10
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/out11
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/out12
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/out13
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/out14
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/out15
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/out16
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/out17
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/out18
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/out19
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/out20
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/out21
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/out22
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/out23
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/out24
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/out25
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/out26
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/out27
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/out28
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/out29
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/out30
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/out31
add wave -noupdate /afu_user_tb/afu_user_uut/uut/stage3/timestamp
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ns} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {215 ns}
